# Generated by Django 5.2.7 on 2025-10-13 10:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_url',
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name='videos'
            ),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name='thumbnails/'
            ),
        ),
    ]
